window:
  padding:
    x: 2
    y: 2
  class:
    instance: Alacritty
    general: Alacritty
  opacity: 0.85

scrolling:
  history: 15000
  multiplier: 5

cursor:
  style:
    shape: Beam 
    blinking: Always
    blink-interval: 750
font:
  normal:
    family: JetBrainsMono Nerd Font
    style:  Bold
  bold:
    family: JetBrainsMono Nerd Font
    style:  Bold
    size: 14
  italic:
    family: JetBrainsMono Nerd Font
    style:  Italic
  bold_italic:
    family: JetBrainsMono Nerd Font
    style: Bold Italic
  size: 13
draw_bold_text_with_bright_colors: true

import:
  - ~/.config/alacritty/catppuccin-mocha.yml

selection:
  save_to_clipboard: false

live_config_reload: true

key_bindings:
  - { key: Return, mods: Super|Shift, action: SpawnNewInstance }
