window:
  padding:
    x: 5
    y: 5
  class:
    instance: Alacritty
    general: Alacritty
  opacity: 0.83

scrolling:
  history: 15000
  multiplier: 5

cursor:
  style:
    shape: Beam 
    blinking: On
    blink-interval: 1000
font:
  normal:
    family: JetBrainsMono Nerd Font
    style:  Regular
  bold:
    family: JetBrainsMono Nerd Font
    style:  Bold
  italic:
    family: JetBrainsMono Nerd Font
    style:  Italic
  bold_italic:
    family: JetBrainsMono Nerd Font
    style: Bold Italic
  size: 12
draw_bold_text_with_bright_colors: true

import:
  - ~/.config/alacritty/catppuccin-mocha.yml

selection:
  save_to_clipboard: false

key_bindings:
  - { key: Return, mods: Super|Shift, action: SpawnNewInstance }
